### ISSUE TITLE
Anti-correlated and correlated data are same

### ISSUE THREAD

**Issue by utsavsinha** [sofiabravo103/builder#2]
When 
python builder.py --correlated -o output1 -s 1000 -d 5
python builder.py --anticorrelated -o output2 -s 1000 -d 5
are run, the output is the same (I think independent dataset). Are those flags functional ?

**Comment by sofiabravo103** [comment]
Yes, the flags are functional. I ran those exact options and the output is not the same. 

I guess that you are looking at the prefix_static output files. Since the current implementation of this generator is able to apply kossman distributions over updates (for instance, the values of the first update of tuple 1 is anticorreleated, or independent, to its next arrival) it is normal behaviour that the prefix_static files are the same, since static data will not have any updates for the entire simulation.

If you look at the prefix_joined file you will get completely different outputs. This is the file with events to tuples with both static and dynamic data. If you look at the prefix_dyn files they are also completely different.

If you would like to have just static correleated, independet, and uniform datasets I think you'll be best off with the original kossman generator. Builder was made to extend kossman's benchmark  to produce dynamic data.

Let me know if there is anything else you need.

**Comment by utsavsinha** [comment]
Thanks ! My mistake, I was looking at prefix_static as you have pointed
out. I will look into the original generator.
